### ISSUE TITLE
Allow camera and microphone access

### ISSUE THREAD

**Issue by KevinAtSesam** [flathub/re.sonny.Tangram#10]
I noticed that when using WhatsApp, I was unable to use the webcam. This apparently applies to all web pages, not just Whatsapp, which you can easily validate using these two pages:

- https://webcamtests.com/
- https://mictests.com/

**Comment by sonnyp** [comment]
https://github.com/sonnyp/tangram#reporting-an-issue

**Comment by KevinAtSesam** [comment]
Ow, it's an upstream issue. 

Also, you might want to duplicate that Readme here because I assumed it was a Flatpak related issue and I didn't check the upstream documentation.
