### ISSUE TITLE
Update WebKitGTK

### ISSUE THREAD

**Issue by garrett** [flathub/re.sonny.Tangram#13]
Tangram currently uses WebKitGTK 2.30.4.

The just-released version of WebKitGTK 2.30.6 contains several security fixes (https://webkitgtk.org/security/WSA-2021-0002.html) and compatibility improvements (https://webkitgtk.org/2021/03/18/webkitgtk2.30.6-released.html).

**Comment by sonnyp** [comment]
`flatpak update re.sonny.Tangram`

Done in https://github.com/flathub/re.sonny.Tangram/pull/14

Not sure why but org.gnome.Platform 40 ships with unstable WebkitGTK 2.31.91

**Comment by garrett** [comment]
Thanks!

Yeah, that's odd. Epiphany 40 is using 2.31.91 as well. I guess it's probably considered an RC. Strange that it isn't 2.32 yet.

![Screenshot from 2021-03-26 11-18-50](https://user-images.githubusercontent.com/10246/112617367-2de74f00-8e25-11eb-9f58-28e0dce74fd5.png)

Hopefully it'll be upgraded to an official stable release in the runtime soon.
