### ISSUE TITLE
Visual error on Ubuntu 19.04

### ISSUE THREAD

**Issue by Kazvko** [flathub/re.sonny.Tangram#6]
As i describe on the link below, when i open the aplication the GTK theme and system fonts doesnt integrate to Tangram, resulting on a visual error. I tried to download from several sources but nothing change between them.
https://plus.diolinux.com.br/t/problemas-com-tangram-flatpak/9950

**Comment by sonnyp** [comment]
Could you start tangram (make sure it's closed first) from the terminal and copy/translate the output

```sh
flatpak run re.sonny.Tangram
```

**Comment by sonnyp** [comment]
The following could also be useful:

```sh
flatpak list
```

```sh
flatpak --version
```

**Comment by Kazvko** [comment]
Kazvko@Inspiron-3442:~$ flatpak run re.sonny.Tangram
Gjs-Message: 22:02:57.993: JS LOG: gjs 1.58.0
Gjs-Message: 22:02:57.993: JS LOG: WebKitGTK 2.26.1

(re.sonny.Tangram:2): Gjs-WARNING **: 22:02:58.047: Some code accessed the property 'env' on the module 'env'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Gjs-Message: 22:02:58.047: JS WARNING: [resource:///re/sonny/Tangram/js/env.js 26]: "env" is read-only
Gjs-Message: 22:02:58.047: JS LOG: env: flatpak
Gjs-Message: 22:02:58.047: JS LOG: data_dir: /home/Kazvko/.var/app/re.sonny.Tangram/data/Tangram
Gjs-Message: 22:02:58.047: JS LOG: cache_dir: /home/Kazvko/.var/app/re.sonny.Tangram/cache/Tangram
Gjs-Message: 22:02:58.047: JS LOG: config_dir: /home/Kazvko/.var/app/re.sonny.Tangram/config/Tangram
Gjs-Message: 22:02:58.048: JS LOG: applications_dir: /home/Kazvko/.local/share/applications
Gjs-Message: 22:02:58.048: JS LOG: keyfile_settings_path: 

(re.sonny.Tangram:2): Gjs-WARNING **: 22:02:58.048: Some code accessed the property 'State' on the module 'state'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Gjs-Message: 22:02:58.158: JS LOG: bin: re.sonny.Tangram
Gjs-Message: 22:02:58.158: JS LOG: default_icon: re.sonny.Tangram

(re.sonny.Tangram:2): Gjs-WARNING **: 22:02:58.160: Some code accessed the property 'list' on the module 'instances'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Gjs-Message: 22:02:58.160: JS WARNING: [resource:///re/sonny/Tangram/js/instances.js 8]: "list" is read-only

(re.sonny.Tangram:2): Gjs-WARNING **: 22:02:58.160: Some code accessed the property 'Instance' on the module 'instances'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Gjs-Message: 22:02:58.160: JS LOG: flag TANGRAM_ENABLE_CUSTOM_APPLICATIONS false
Gjs-Message: 22:02:58.160: JS LOG: flag TANGRAM_ENABLE_CUSTOM_ICONS false

(re.sonny.Tangram:2): Gjs-WARNING **: 22:02:58.737: Some code accessed the property 'application' on the module 'application'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Gjs-Message: 22:02:58.737: JS WARNING: [resource:///re/sonny/Tangram/js/application.js 26]: "application" is read-only
Gjs-Message: 22:02:58.743: JS LOG: programInvocationName: /app/bin/re.sonny.Tangram
Gjs-Message: 22:02:58.743: JS LOG: _: /usr/bin/flatpak
Gjs-Message: 22:02:58.744: JS LOG: pkg.pkgdatadir: /app/share/Tangram
Gjs-Message: 22:02:58.744: JS LOG: pkg.pkglibdir: /app/lib/Tangram
Gjs-Message: 22:02:58.744: JS LOG: pkg.datadir: /app/share
Gjs-Message: 22:02:58.744: JS LOG: pkg.version: 1.2.0
Gjs-Message: 22:02:58.744: JS LOG: pkg.name: re.sonny.Tangram
Gjs-Message: 22:02:58.744: JS LOG: pkg.libdir: /app/lib
Gjs-Message: 22:02:58.744: JS LOG: pkg.localedir: /app/share/locale
Gjs-Message: 22:02:58.744: JS LOG: pkg.prefix: /app
Gjs-Message: 22:02:58.744: JS LOG: pkg.moduledir: resource:///re/sonny/Tangram/js
Gjs-Message: 22:02:58.744: JS LOG: argv: /app/bin/re.sonny.Tangram
Gjs-Message: 22:02:58.766: JS LOG: Migrated: false
Gjs-Message: 22:03:02.490: JS LOG: profile.title: Tangram
Gjs-Message: 22:03:02.490: JS LOG: profile.application_id: re.sonny.Tangram
Gjs-Message: 22:03:02.490: JS LOG: profile.settings: /re/sonny/Tangram/

(process:33): libsoup-WARNING **: 22:03:08.956: Failed to execute query: table soup_hsts_policies already exists

(process:28): libsoup-WARNING **: 22:03:08.956: Failed to execute query: table soup_hsts_policies already exists

(process:23): libsoup-WARNING **: 22:03:08.956: Failed to execute query: table soup_hsts_policies already exists

(process:23): libsoup-WARNING **: 22:03:08.957: Failed to execute query: database is locked

(process:33): libsoup-WARNING **: 22:03:08.957: Failed to execute query: database is locked

(process:23): libsoup-WARNING **: 22:03:08.957: Failed to execute query: table soup_hsts_policies already exists

(process:28): libsoup-WARNING **: 22:03:08.957: Failed to execute query: database is locked

(process:28): libsoup-WARNING **: 22:03:08.957: Failed to execute query: table soup_hsts_policies already exists

(process:23): libsoup-WARNING **: 22:03:08.958: Failed to execute query: database is locked

(process:33): libsoup-WARNING **: 22:03:08.958: Failed to execute query: table soup_hsts_policies already exists

(process:23): libsoup-WARNING **: 22:03:08.958: Failed to execute query: table soup_hsts_policies already exists

(process:28): libsoup-WARNING **: 22:03:08.958: Failed to execute query: database is locked

(process:28): libsoup-WARNING **: 22:03:08.958: Failed to execute query: table soup_hsts_policies already exists

(process:33): libsoup-WARNING **: 22:03:08.958: Failed to execute query: database is locked

(process:23): libsoup-WARNING **: 22:03:08.958: Failed to execute query: database is locked

(process:23): libsoup-WARNING **: 22:03:08.958: Failed to execute query: table soup_hsts_policies already exists

(process:23): libsoup-WARNING **: 22:03:08.958: Failed to execute query: database is locked

(process:23): libsoup-WARNING **: 22:03:08.959: Failed to execute query: table soup_hsts_policies already exists

(process:33): libsoup-WARNING **: 22:03:08.959: Failed to execute query: table soup_hsts_policies already exists

(process:33): libsoup-WARNING **: 22:03:08.959: Failed to execute query: database is locked

(process:28): libsoup-WARNING **: 22:03:08.958: Failed to execute query: database is locked

(process:23): libsoup-WARNING **: 22:03:08.959: Failed to execute query: database is locked

(process:28): libsoup-WARNING **: 22:03:08.959: Failed to execute query: table soup_hsts_policies already exists

(process:28): libsoup-WARNING **: 22:03:08.959: Failed to execute query: database is locked

(process:33): libsoup-WARNING **: 22:03:08.959: Failed to execute query: table soup_hsts_policies already exists

(process:33): libsoup-WARNING **: 22:03:08.959: Failed to execute query: database is locked

(process:28): libsoup-WARNING **: 22:03:08.960: Failed to execute query: table soup_hsts_policies already exists

(process:28): libsoup-WARNING **: 22:03:08.960: Failed to execute query: database is locked

(process:33): libsoup-WARNING **: 22:03:08.960: Failed to execute query: table soup_hsts_policies already exists
Memory pressure relief: Total: res = 12587008/12369920/-217088, res+swap = 8118272/8118272/0
Memory pressure relief: Total: res = 12652544/12435456/-217088, res+swap = 8179712/8179712/0
Memory pressure relief: Total: res = 12587008/12378112/-208896, res+swap = 8118272/8118272/0
Memory pressure relief: Total: res = 12570624/12374016/-196608, res+swap = 8163328/8163328/0

kazvko@Inspiron-3442:~$ flatpak --version
Flatpak 1.4.3
kazvko@Inspiron-3442:~$ flatpak list
Nome                                    ID de aplicativo                                    Versão   Ramo   Instalação
The Passage                             com.endlessnetwork.passage                          1.34     stable system
Foliate                                 com.github.johnfactotum.Foliate                     1.5.3    stable system
Steam                                   com.valvesoftware.Steam                             1.0.0.61 stable system
Freedesktop Platform                    org.freedesktop.Platform                            18.08.36 18.08  system
Freedesktop Platform                    org.freedesktop.Platform                            19.08.2  19.08  system
i386                                    org.freedesktop.Platform.Compat.i386                         19.08  system
default                                 org.freedesktop.Platform.GL.default                          19.08  system
default                                 org.freedesktop.Platform.GL32.default                        19.08  system
Intel VAAPI Driver                      org.freedesktop.Platform.VAAPI.Intel                         1.6    system
Intel                                   org.freedesktop.Platform.VAAPI.Intel                         18.08  system
Intel                                   org.freedesktop.Platform.VAAPI.Intel                         19.08  system
FFmpeg extension                        org.freedesktop.Platform.ffmpeg                              1.6    system
html5-codecs                            org.freedesktop.Platform.html5-codecs                        18.08  system
openh264                                org.freedesktop.Platform.openh264                            19.08  system
GNOME Application Platform version 3.28 org.gnome.Platform                                           3.28   system
GNOME Application Platform version 3.32 org.gnome.Platform                                           3.32   system
GNOME Application Platform version 3.34 org.gnome.Platform                                           3.34   system
High Sierra GTK Theme                   org.gtk.Gtk3theme.High-Sierra-Dark                           3.22   system
JASP                                    org.jaspstats.JASP                                  0.11.0   stable system
KDE Application Platform                org.kde.Platform                                             5.12   system
QGnomePlatform                          org.kde.PlatformTheme.QGnomePlatform                         5.12   system
KDE Software Development Kit            org.kde.Sdk                                                  5.12   system
QGnomePlatform-decoration               org.kde.WaylandDecoration.QGnomePlatform-decoration          5.12   system
LibreOffice                             org.libreoffice.LibreOffice                         6.3.2.2  stable system
PulseAudio Volume Control               org.pulseaudio.pavucontrol                          4.0      stable system
Tangram                                 re.sonny.Tangram                                    1.2.0    stable system

**Comment by sonnyp** [comment]
Looks good.

It only happens with Tangram right? Can you reproduce with other GTK flatpak applications?

**Comment by Kazvko** [comment]
Actually with some flatpak's it happens, and others not. Here's some examples:

kazvko@Inspiron-3442:~$ flatpak run org.pulseaudio.pavucontrol
Gtk-Message: 10:22:50.405: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:22:50.405: Failed to load module "canberra-gtk-module"

kazvko@Inspiron-3442:~$ flatpak run org.jaspstats.JASP  
Gtk-Message: 10:24:23.073: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:24:23.073: Failed to load module "canberra-gtk-module"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
Property 'data'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle 'mode', use qRegisterMetaType to register it.
Don't know how to handle 'format', use qRegisterMetaType to register it.
Don't know how to handle 'mirroring', use qRegisterMetaType to register it.
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'SplitView_QMLTYPE_89_QML_168' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'SplitView_QMLTYPE_89_QML_168' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'SplitView_QMLTYPE_89_QML_168' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'SplitView_QMLTYPE_89_QML_168' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'SplitView_QMLTYPE_89_QML_168' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'SplitView_QMLTYPE_89_QML_168' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'gradient'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'userScripts'' of object 'QQuickWebEngineProfile' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'transports'' of object 'QQmlWebChannel' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'registeredObjects'' of object 'QQmlWebChannel' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'userScripts'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem_QML_170' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem_QML_170' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem_QML_170' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem_QML_170' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem_QML_170' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem_QML_170' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/

kazvko@Inspiron-3442:~$ flatpak run com.github.johnfactotum.Foliate
Gjs-Message: 10:27:03.209: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 72]: test for equality (==) mistyped as assignment (=)?
Portal call failed: Failed to start command: Falha ao executar processo filho “dict” (Arquivo ou diretório inexistente)
Portal call failed: Failed to start command: Falha ao executar processo filho “espeak” (Arquivo ou diretório inexistente)
Portal call failed: Failed to start command: Falha ao executar processo filho “festival” (Arquivo ou diretório inexistente)
Gjs-Message: 10:27:05.431: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 2406]: reference to undefined property "isFullscreen"
Gjs-Message: 10:27:06.520: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 2127]: reference to undefined property "atStart"

**Comment by Kazvko** [comment]
The last one, "Foliate" has the same visual error.

**Comment by Kazvko** [comment]
Ok, I did it. I needed to name my Gnome Tweaks theme as the flatpak theme. That done tangram as well as other faulty GTK applications were able to integrate the theme.

**Comment by Kazvko** [comment]
Não, mas o processo de resolução foi o que disse acima. Baixar o mesmo tema em flatpak, nomea-lo da mesma forma que o tema que utiliza e depois seleciona-lo e reiniciar o Gnome.
